### ISSUE TITLE
fix/macOsMojave

### ISSUE THREAD

**Issue by madintist** [madintist/dev_config#34]
# Issue

The current setup doesn't work correctly on macOS Mojave. Fix it.

## Todo

- [x] `gpg-agent` won't install
  - `Error: No available formula with the name "gpg-agent"`
- [x] `manifold-cli` won't install
  - `make: *** No rule to make target `binary-darwin-amd64'.  Stop.`
- [x] `neovim` won't install
  - `Download failed: https://luarocks.org/luabitop-1.0.2-1.src.rock`
- [x] `node` won't install due to an error with the `python@2` and `zlib` packages. Homebrew/homebrew-core#29176
  - Pretty sure we can fix this by making sure that `python@2` is correctly installed _before_ installing the `node` package.
  - I've got `node` installed at the moment. Just want to make sure that we can run the `setup` script from a clean environment and it'll still install.

**Comment by madintist** [comment]
## Current Bugs

- [ ] `node` won't install due to an error with the `python@2` and `zlib` packages. Homebrew/homebrew-core#29176
- [ ] The `./homebrew/setup` script tries to install packages that have already been installed.

**Comment by madintist** [comment]
Try installing `manifold-cli` with the `curl` installer. It seems to work that way. 😄

**Comment by madintist** [comment]
Neovim has issues due to a bug in Homebrew from August: https://github.com/Homebrew/homebrew-core/pull/32204

Just gotta wait on that PR to get merged.
